// Package catalogapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package catalogapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Diagnosis defines model for Diagnosis.
type Diagnosis struct {
	Code      string             `json:"code"`
	CreatedAt time.Time          `json:"created_at"`
	DeletedAt *time.Time         `json:"deleted_at"`
	ID        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// DiagnosisInput defines model for DiagnosisInput.
type DiagnosisInput struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

// DiagnosisPage defines model for DiagnosisPage.
type DiagnosisPage struct {
	Items  []Diagnosis `json:"items"`
	Limit  int         `json:"limit"`
	Offset int         `json:"offset"`
	Total  int         `json:"total"`
}

// Error defines model for Error.
type Error struct {
	Error ErrorDetail `json:"error"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Code    string             `json:"code"`
	Fields  *map[string]string `json:"fields,omitempty"`
	Message string             `json:"message"`
}

// ImportInput defines model for ImportInput.
type ImportInput struct {
	Diagnoses []DiagnosisInput `json:"diagnoses"`
}

// ImportResult defines model for ImportResult.
type ImportResult struct {
	Items []Diagnosis `json:"items"`
}

// ListDiagnosesParams defines parameters for ListDiagnoses.
type ListDiagnosesParams struct {
	Limit          *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset         *int    `form:"offset,omitempty" json:"offset,omitempty"`
	Q              *string `form:"q,omitempty" json:"q,omitempty"`
	IncludeDeleted *bool   `form:"include_deleted,omitempty" json:"include_deleted,omitempty"`
}

// CreateDiagnosisJSONRequestBody defines body for CreateDiagnosis for application/json ContentType.
type CreateDiagnosisJSONRequestBody = DiagnosisInput

// ImportDiagnosesJSONRequestBody defines body for ImportDiagnoses for application/json ContentType.
type ImportDiagnosesJSONRequestBody = ImportInput

// UpdateDiagnosisJSONRequestBody defines body for UpdateDiagnosis for application/json ContentType.
type UpdateDiagnosisJSONRequestBody = DiagnosisInput

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// ListDiagnoses Список активных записей
	//
	// Corresponds with GET /api/v1/diagnoses (the `ListDiagnoses` operationId).
	ListDiagnoses(ctx context.Context, params *ListDiagnosesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateDiagnosisWithBody Создать запись
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /api/v1/diagnoses (the `CreateDiagnosis` operationId).
	CreateDiagnosisWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateDiagnosis Создать запись
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /api/v1/diagnoses (the `CreateDiagnosis` operationId).
	CreateDiagnosis(ctx context.Context, body CreateDiagnosisJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ImportDiagnosesWithBody Импортировать диагнозы из выбранного JSON-файла одной транзакцией
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /api/v1/diagnoses/import (the `ImportDiagnoses` operationId).
	ImportDiagnosesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ImportDiagnoses Импортировать диагнозы из выбранного JSON-файла одной транзакцией
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /api/v1/diagnoses/import (the `ImportDiagnoses` operationId).
	ImportDiagnoses(ctx context.Context, body ImportDiagnosesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteDiagnosis Мягкое удаление
	//
	// Corresponds with DELETE /api/v1/diagnoses/{id} (the `DeleteDiagnosis` operationId).
	DeleteDiagnosis(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDiagnosis Карточка, включая мягко удалённые записи
	//
	// Corresponds with GET /api/v1/diagnoses/{id} (the `GetDiagnosis` operationId).
	GetDiagnosis(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateDiagnosisWithBody Полностью обновить активную запись
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PUT /api/v1/diagnoses/{id} (the `UpdateDiagnosis` operationId).
	UpdateDiagnosisWithBody(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateDiagnosis Полностью обновить активную запись
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PUT /api/v1/diagnoses/{id} (the `UpdateDiagnosis` operationId).
	UpdateDiagnosis(ctx context.Context, id openapi_types.UUID, body UpdateDiagnosisJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// ListDiagnoses Список активных записей
//
// Corresponds with GET /api/v1/diagnoses (the `ListDiagnoses` operationId).
func (c *Client) ListDiagnoses(ctx context.Context, params *ListDiagnosesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListDiagnosesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateDiagnosisWithBody Создать запись
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /api/v1/diagnoses (the `CreateDiagnosis` operationId).
func (c *Client) CreateDiagnosisWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateDiagnosisRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateDiagnosis Создать запись
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /api/v1/diagnoses (the `CreateDiagnosis` operationId).
func (c *Client) CreateDiagnosis(ctx context.Context, body CreateDiagnosisJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateDiagnosisRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ImportDiagnosesWithBody Импортировать диагнозы из выбранного JSON-файла одной транзакцией
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /api/v1/diagnoses/import (the `ImportDiagnoses` operationId).
func (c *Client) ImportDiagnosesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewImportDiagnosesRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ImportDiagnoses Импортировать диагнозы из выбранного JSON-файла одной транзакцией
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /api/v1/diagnoses/import (the `ImportDiagnoses` operationId).
func (c *Client) ImportDiagnoses(ctx context.Context, body ImportDiagnosesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewImportDiagnosesRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteDiagnosis Мягкое удаление
//
// Corresponds with DELETE /api/v1/diagnoses/{id} (the `DeleteDiagnosis` operationId).
func (c *Client) DeleteDiagnosis(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteDiagnosisRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetDiagnosis Карточка, включая мягко удалённые записи
//
// Corresponds with GET /api/v1/diagnoses/{id} (the `GetDiagnosis` operationId).
func (c *Client) GetDiagnosis(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDiagnosisRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpdateDiagnosisWithBody Полностью обновить активную запись
//
// Takes any type of body and a specified content type.
//
// Corresponds with PUT /api/v1/diagnoses/{id} (the `UpdateDiagnosis` operationId).
func (c *Client) UpdateDiagnosisWithBody(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateDiagnosisRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpdateDiagnosis Полностью обновить активную запись
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PUT /api/v1/diagnoses/{id} (the `UpdateDiagnosis` operationId).
func (c *Client) UpdateDiagnosis(ctx context.Context, id openapi_types.UUID, body UpdateDiagnosisJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateDiagnosisRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListDiagnosesRequest constructs an http.Request for the ListDiagnoses method
func NewListDiagnosesRequest(server string, params *ListDiagnosesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/diagnoses")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "offset", *params.Offset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Q != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "q", *params.Q, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.IncludeDeleted != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "include_deleted", *params.IncludeDeleted, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "boolean", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateDiagnosisRequest calls the generic CreateDiagnosis builder with application/json body
func NewCreateDiagnosisRequest(server string, body CreateDiagnosisJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateDiagnosisRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateDiagnosisRequestWithBody constructs an http.Request for the CreateDiagnosis method, with any body, and a specified content type
func NewCreateDiagnosisRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/diagnoses")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewImportDiagnosesRequest calls the generic ImportDiagnoses builder with application/json body
func NewImportDiagnosesRequest(server string, body ImportDiagnosesJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewImportDiagnosesRequestWithBody(server, "application/json", bodyReader)
}

// NewImportDiagnosesRequestWithBody constructs an http.Request for the ImportDiagnoses method, with any body, and a specified content type
func NewImportDiagnosesRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/diagnoses/import")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteDiagnosisRequest constructs an http.Request for the DeleteDiagnosis method
func NewDeleteDiagnosisRequest(server string, id openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/diagnoses/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetDiagnosisRequest constructs an http.Request for the GetDiagnosis method
func NewGetDiagnosisRequest(server string, id openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/diagnoses/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateDiagnosisRequest calls the generic UpdateDiagnosis builder with application/json body
func NewUpdateDiagnosisRequest(server string, id openapi_types.UUID, body UpdateDiagnosisJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateDiagnosisRequestWithBody(server, id, "application/json", bodyReader)
}

// NewUpdateDiagnosisRequestWithBody constructs an http.Request for the UpdateDiagnosis method, with any body, and a specified content type
func NewUpdateDiagnosisRequestWithBody(server string, id openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/diagnoses/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// ListDiagnosesWithResponse Список активных записей
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/diagnoses (the `ListDiagnoses` operationId).
	ListDiagnosesWithResponse(ctx context.Context, params *ListDiagnosesParams, reqEditors ...RequestEditorFn) (*ListDiagnosesResponse, error)

	// CreateDiagnosisWithBodyWithResponse Создать запись
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1/diagnoses (the `CreateDiagnosis` operationId).
	CreateDiagnosisWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateDiagnosisResponse, error)

	// CreateDiagnosisWithResponse Создать запись
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1/diagnoses (the `CreateDiagnosis` operationId).
	CreateDiagnosisWithResponse(ctx context.Context, body CreateDiagnosisJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateDiagnosisResponse, error)

	// ImportDiagnosesWithBodyWithResponse Импортировать диагнозы из выбранного JSON-файла одной транзакцией
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1/diagnoses/import (the `ImportDiagnoses` operationId).
	ImportDiagnosesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ImportDiagnosesResponse, error)

	// ImportDiagnosesWithResponse Импортировать диагнозы из выбранного JSON-файла одной транзакцией
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1/diagnoses/import (the `ImportDiagnoses` operationId).
	ImportDiagnosesWithResponse(ctx context.Context, body ImportDiagnosesJSONRequestBody, reqEditors ...RequestEditorFn) (*ImportDiagnosesResponse, error)

	// DeleteDiagnosisWithResponse Мягкое удаление
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /api/v1/diagnoses/{id} (the `DeleteDiagnosis` operationId).
	DeleteDiagnosisWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*DeleteDiagnosisResponse, error)

	// GetDiagnosisWithResponse Карточка, включая мягко удалённые записи
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/diagnoses/{id} (the `GetDiagnosis` operationId).
	GetDiagnosisWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetDiagnosisResponse, error)

	// UpdateDiagnosisWithBodyWithResponse Полностью обновить активную запись
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /api/v1/diagnoses/{id} (the `UpdateDiagnosis` operationId).
	UpdateDiagnosisWithBodyWithResponse(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateDiagnosisResponse, error)

	// UpdateDiagnosisWithResponse Полностью обновить активную запись
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /api/v1/diagnoses/{id} (the `UpdateDiagnosis` operationId).
	UpdateDiagnosisWithResponse(ctx context.Context, id openapi_types.UUID, body UpdateDiagnosisJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateDiagnosisResponse, error)
}

type ListDiagnosesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *DiagnosisPage
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Error
	// JSON415 the response for an HTTP 415 `application/json` response
	JSON415 *Error
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *Error
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListDiagnosesResponse) GetJSON200() *DiagnosisPage {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r ListDiagnosesResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r ListDiagnosesResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r ListDiagnosesResponse) GetJSON409() *Error {
	return r.JSON409
}

// GetJSON415 returns the response for an HTTP 415 `application/json` response
func (r ListDiagnosesResponse) GetJSON415() *Error {
	return r.JSON415
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r ListDiagnosesResponse) GetJSON500() *Error {
	return r.JSON500
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r ListDiagnosesResponse) GetJSON503() *Error {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r ListDiagnosesResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListDiagnosesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListDiagnosesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListDiagnosesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateDiagnosisResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *Diagnosis
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Error
	// JSON415 the response for an HTTP 415 `application/json` response
	JSON415 *Error
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *Error
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *Error
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r CreateDiagnosisResponse) GetJSON201() *Diagnosis {
	return r.JSON201
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r CreateDiagnosisResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r CreateDiagnosisResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r CreateDiagnosisResponse) GetJSON409() *Error {
	return r.JSON409
}

// GetJSON415 returns the response for an HTTP 415 `application/json` response
func (r CreateDiagnosisResponse) GetJSON415() *Error {
	return r.JSON415
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r CreateDiagnosisResponse) GetJSON500() *Error {
	return r.JSON500
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r CreateDiagnosisResponse) GetJSON503() *Error {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r CreateDiagnosisResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreateDiagnosisResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateDiagnosisResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateDiagnosisResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ImportDiagnosesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ImportResult
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Error
	// JSON415 the response for an HTTP 415 `application/json` response
	JSON415 *Error
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *Error
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ImportDiagnosesResponse) GetJSON200() *ImportResult {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r ImportDiagnosesResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r ImportDiagnosesResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r ImportDiagnosesResponse) GetJSON409() *Error {
	return r.JSON409
}

// GetJSON415 returns the response for an HTTP 415 `application/json` response
func (r ImportDiagnosesResponse) GetJSON415() *Error {
	return r.JSON415
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r ImportDiagnosesResponse) GetJSON500() *Error {
	return r.JSON500
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r ImportDiagnosesResponse) GetJSON503() *Error {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r ImportDiagnosesResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ImportDiagnosesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ImportDiagnosesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ImportDiagnosesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteDiagnosisResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Error
	// JSON415 the response for an HTTP 415 `application/json` response
	JSON415 *Error
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *Error
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *Error
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r DeleteDiagnosisResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r DeleteDiagnosisResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r DeleteDiagnosisResponse) GetJSON409() *Error {
	return r.JSON409
}

// GetJSON415 returns the response for an HTTP 415 `application/json` response
func (r DeleteDiagnosisResponse) GetJSON415() *Error {
	return r.JSON415
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r DeleteDiagnosisResponse) GetJSON500() *Error {
	return r.JSON500
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r DeleteDiagnosisResponse) GetJSON503() *Error {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r DeleteDiagnosisResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DeleteDiagnosisResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteDiagnosisResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteDiagnosisResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetDiagnosisResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Diagnosis
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Error
	// JSON415 the response for an HTTP 415 `application/json` response
	JSON415 *Error
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *Error
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetDiagnosisResponse) GetJSON200() *Diagnosis {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r GetDiagnosisResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetDiagnosisResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r GetDiagnosisResponse) GetJSON409() *Error {
	return r.JSON409
}

// GetJSON415 returns the response for an HTTP 415 `application/json` response
func (r GetDiagnosisResponse) GetJSON415() *Error {
	return r.JSON415
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r GetDiagnosisResponse) GetJSON500() *Error {
	return r.JSON500
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r GetDiagnosisResponse) GetJSON503() *Error {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r GetDiagnosisResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetDiagnosisResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDiagnosisResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetDiagnosisResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UpdateDiagnosisResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Diagnosis
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Error
	// JSON415 the response for an HTTP 415 `application/json` response
	JSON415 *Error
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *Error
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r UpdateDiagnosisResponse) GetJSON200() *Diagnosis {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r UpdateDiagnosisResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r UpdateDiagnosisResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r UpdateDiagnosisResponse) GetJSON409() *Error {
	return r.JSON409
}

// GetJSON415 returns the response for an HTTP 415 `application/json` response
func (r UpdateDiagnosisResponse) GetJSON415() *Error {
	return r.JSON415
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r UpdateDiagnosisResponse) GetJSON500() *Error {
	return r.JSON500
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r UpdateDiagnosisResponse) GetJSON503() *Error {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r UpdateDiagnosisResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r UpdateDiagnosisResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateDiagnosisResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UpdateDiagnosisResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListDiagnosesWithResponse Список активных записей
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/diagnoses (the `ListDiagnoses` operationId).
func (c *ClientWithResponses) ListDiagnosesWithResponse(ctx context.Context, params *ListDiagnosesParams, reqEditors ...RequestEditorFn) (*ListDiagnosesResponse, error) {
	rsp, err := c.ListDiagnoses(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListDiagnosesResponse(rsp)
}

// CreateDiagnosisWithBodyWithResponse Создать запись
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1/diagnoses (the `CreateDiagnosis` operationId).
func (c *ClientWithResponses) CreateDiagnosisWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateDiagnosisResponse, error) {
	rsp, err := c.CreateDiagnosisWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateDiagnosisResponse(rsp)
}

// CreateDiagnosisWithResponse Создать запись
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1/diagnoses (the `CreateDiagnosis` operationId).
func (c *ClientWithResponses) CreateDiagnosisWithResponse(ctx context.Context, body CreateDiagnosisJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateDiagnosisResponse, error) {
	rsp, err := c.CreateDiagnosis(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateDiagnosisResponse(rsp)
}

// ImportDiagnosesWithBodyWithResponse Импортировать диагнозы из выбранного JSON-файла одной транзакцией
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1/diagnoses/import (the `ImportDiagnoses` operationId).
func (c *ClientWithResponses) ImportDiagnosesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ImportDiagnosesResponse, error) {
	rsp, err := c.ImportDiagnosesWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseImportDiagnosesResponse(rsp)
}

// ImportDiagnosesWithResponse Импортировать диагнозы из выбранного JSON-файла одной транзакцией
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1/diagnoses/import (the `ImportDiagnoses` operationId).
func (c *ClientWithResponses) ImportDiagnosesWithResponse(ctx context.Context, body ImportDiagnosesJSONRequestBody, reqEditors ...RequestEditorFn) (*ImportDiagnosesResponse, error) {
	rsp, err := c.ImportDiagnoses(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseImportDiagnosesResponse(rsp)
}

// DeleteDiagnosisWithResponse Мягкое удаление
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /api/v1/diagnoses/{id} (the `DeleteDiagnosis` operationId).
func (c *ClientWithResponses) DeleteDiagnosisWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*DeleteDiagnosisResponse, error) {
	rsp, err := c.DeleteDiagnosis(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteDiagnosisResponse(rsp)
}

// GetDiagnosisWithResponse Карточка, включая мягко удалённые записи
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/diagnoses/{id} (the `GetDiagnosis` operationId).
func (c *ClientWithResponses) GetDiagnosisWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetDiagnosisResponse, error) {
	rsp, err := c.GetDiagnosis(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDiagnosisResponse(rsp)
}

// UpdateDiagnosisWithBodyWithResponse Полностью обновить активную запись
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /api/v1/diagnoses/{id} (the `UpdateDiagnosis` operationId).
func (c *ClientWithResponses) UpdateDiagnosisWithBodyWithResponse(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateDiagnosisResponse, error) {
	rsp, err := c.UpdateDiagnosisWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateDiagnosisResponse(rsp)
}

// UpdateDiagnosisWithResponse Полностью обновить активную запись
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /api/v1/diagnoses/{id} (the `UpdateDiagnosis` operationId).
func (c *ClientWithResponses) UpdateDiagnosisWithResponse(ctx context.Context, id openapi_types.UUID, body UpdateDiagnosisJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateDiagnosisResponse, error) {
	rsp, err := c.UpdateDiagnosis(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateDiagnosisResponse(rsp)
}

// ParseListDiagnosesResponse parses an HTTP response from a ListDiagnosesWithResponse call
func ParseListDiagnosesResponse(rsp *http.Response) (*ListDiagnosesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListDiagnosesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DiagnosisPage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 415:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON415 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseCreateDiagnosisResponse parses an HTTP response from a CreateDiagnosisWithResponse call
func ParseCreateDiagnosisResponse(rsp *http.Response) (*CreateDiagnosisResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateDiagnosisResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Diagnosis
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 415:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON415 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseImportDiagnosesResponse parses an HTTP response from a ImportDiagnosesWithResponse call
func ParseImportDiagnosesResponse(rsp *http.Response) (*ImportDiagnosesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ImportDiagnosesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ImportResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 415:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON415 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseDeleteDiagnosisResponse parses an HTTP response from a DeleteDiagnosisWithResponse call
func ParseDeleteDiagnosisResponse(rsp *http.Response) (*DeleteDiagnosisResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteDiagnosisResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 415:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON415 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseGetDiagnosisResponse parses an HTTP response from a GetDiagnosisWithResponse call
func ParseGetDiagnosisResponse(rsp *http.Response) (*GetDiagnosisResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDiagnosisResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Diagnosis
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 415:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON415 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseUpdateDiagnosisResponse parses an HTTP response from a UpdateDiagnosisWithResponse call
func ParseUpdateDiagnosisResponse(rsp *http.Response) (*UpdateDiagnosisResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateDiagnosisResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Diagnosis
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 415:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON415 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}
