// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gorilla/mux"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Diagnosis defines model for Diagnosis.
type Diagnosis struct {
	Code      string             `json:"code"`
	CreatedAt time.Time          `json:"created_at"`
	DeletedAt *time.Time         `json:"deleted_at"`
	ID        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// DiagnosisInput defines model for DiagnosisInput.
type DiagnosisInput struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

// DiagnosisPage defines model for DiagnosisPage.
type DiagnosisPage struct {
	Items  []Diagnosis `json:"items"`
	Limit  int         `json:"limit"`
	Offset int         `json:"offset"`
	Total  int         `json:"total"`
}

// Error defines model for Error.
type Error struct {
	Error ErrorDetail `json:"error"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Code    string             `json:"code"`
	Fields  *map[string]string `json:"fields,omitempty"`
	Message string             `json:"message"`
}

// ImportInput defines model for ImportInput.
type ImportInput struct {
	Diagnoses []DiagnosisInput `json:"diagnoses"`
}

// ImportResult defines model for ImportResult.
type ImportResult struct {
	Items []Diagnosis `json:"items"`
}

// ListDiagnosesParams defines parameters for ListDiagnoses.
type ListDiagnosesParams struct {
	Limit          *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset         *int    `form:"offset,omitempty" json:"offset,omitempty"`
	Q              *string `form:"q,omitempty" json:"q,omitempty"`
	IncludeDeleted *bool   `form:"include_deleted,omitempty" json:"include_deleted,omitempty"`
}

// CreateDiagnosisJSONRequestBody defines body for CreateDiagnosis for application/json ContentType.
type CreateDiagnosisJSONRequestBody = DiagnosisInput

// ImportDiagnosesJSONRequestBody defines body for ImportDiagnoses for application/json ContentType.
type ImportDiagnosesJSONRequestBody = ImportInput

// UpdateDiagnosisJSONRequestBody defines body for UpdateDiagnosis for application/json ContentType.
type UpdateDiagnosisJSONRequestBody = DiagnosisInput

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// ListDiagnoses Список активных записей
	//
	// Corresponds with GET /api/v1/diagnoses (the `ListDiagnoses` operationId).
	ListDiagnoses(ctx context.Context, params *ListDiagnosesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateDiagnosisWithBody Создать запись
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /api/v1/diagnoses (the `CreateDiagnosis` operationId).
	CreateDiagnosisWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateDiagnosis Создать запись
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /api/v1/diagnoses (the `CreateDiagnosis` operationId).
	CreateDiagnosis(ctx context.Context, body CreateDiagnosisJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ImportDiagnosesWithBody Импортировать диагнозы из выбранного JSON-файла одной транзакцией
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /api/v1/diagnoses/import (the `ImportDiagnoses` operationId).
	ImportDiagnosesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ImportDiagnoses Импортировать диагнозы из выбранного JSON-файла одной транзакцией
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /api/v1/diagnoses/import (the `ImportDiagnoses` operationId).
	ImportDiagnoses(ctx context.Context, body ImportDiagnosesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteDiagnosis Мягкое удаление
	//
	// Corresponds with DELETE /api/v1/diagnoses/{id} (the `DeleteDiagnosis` operationId).
	DeleteDiagnosis(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDiagnosis Карточка, включая мягко удалённые записи
	//
	// Corresponds with GET /api/v1/diagnoses/{id} (the `GetDiagnosis` operationId).
	GetDiagnosis(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateDiagnosisWithBody Полностью обновить активную запись
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PUT /api/v1/diagnoses/{id} (the `UpdateDiagnosis` operationId).
	UpdateDiagnosisWithBody(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateDiagnosis Полностью обновить активную запись
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PUT /api/v1/diagnoses/{id} (the `UpdateDiagnosis` operationId).
	UpdateDiagnosis(ctx context.Context, id openapi_types.UUID, body UpdateDiagnosisJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// ListDiagnoses Список активных записей
//
// Corresponds with GET /api/v1/diagnoses (the `ListDiagnoses` operationId).
func (c *Client) ListDiagnoses(ctx context.Context, params *ListDiagnosesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListDiagnosesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateDiagnosisWithBody Создать запись
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /api/v1/diagnoses (the `CreateDiagnosis` operationId).
func (c *Client) CreateDiagnosisWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateDiagnosisRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateDiagnosis Создать запись
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /api/v1/diagnoses (the `CreateDiagnosis` operationId).
func (c *Client) CreateDiagnosis(ctx context.Context, body CreateDiagnosisJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateDiagnosisRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ImportDiagnosesWithBody Импортировать диагнозы из выбранного JSON-файла одной транзакцией
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /api/v1/diagnoses/import (the `ImportDiagnoses` operationId).
func (c *Client) ImportDiagnosesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewImportDiagnosesRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ImportDiagnoses Импортировать диагнозы из выбранного JSON-файла одной транзакцией
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /api/v1/diagnoses/import (the `ImportDiagnoses` operationId).
func (c *Client) ImportDiagnoses(ctx context.Context, body ImportDiagnosesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewImportDiagnosesRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteDiagnosis Мягкое удаление
//
// Corresponds with DELETE /api/v1/diagnoses/{id} (the `DeleteDiagnosis` operationId).
func (c *Client) DeleteDiagnosis(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteDiagnosisRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetDiagnosis Карточка, включая мягко удалённые записи
//
// Corresponds with GET /api/v1/diagnoses/{id} (the `GetDiagnosis` operationId).
func (c *Client) GetDiagnosis(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDiagnosisRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpdateDiagnosisWithBody Полностью обновить активную запись
//
// Takes any type of body and a specified content type.
//
// Corresponds with PUT /api/v1/diagnoses/{id} (the `UpdateDiagnosis` operationId).
func (c *Client) UpdateDiagnosisWithBody(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateDiagnosisRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpdateDiagnosis Полностью обновить активную запись
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PUT /api/v1/diagnoses/{id} (the `UpdateDiagnosis` operationId).
func (c *Client) UpdateDiagnosis(ctx context.Context, id openapi_types.UUID, body UpdateDiagnosisJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateDiagnosisRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListDiagnosesRequest constructs an http.Request for the ListDiagnoses method
func NewListDiagnosesRequest(server string, params *ListDiagnosesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/diagnoses")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "offset", *params.Offset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Q != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "q", *params.Q, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.IncludeDeleted != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "include_deleted", *params.IncludeDeleted, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "boolean", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateDiagnosisRequest calls the generic CreateDiagnosis builder with application/json body
func NewCreateDiagnosisRequest(server string, body CreateDiagnosisJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateDiagnosisRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateDiagnosisRequestWithBody constructs an http.Request for the CreateDiagnosis method, with any body, and a specified content type
func NewCreateDiagnosisRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/diagnoses")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewImportDiagnosesRequest calls the generic ImportDiagnoses builder with application/json body
func NewImportDiagnosesRequest(server string, body ImportDiagnosesJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewImportDiagnosesRequestWithBody(server, "application/json", bodyReader)
}

// NewImportDiagnosesRequestWithBody constructs an http.Request for the ImportDiagnoses method, with any body, and a specified content type
func NewImportDiagnosesRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/diagnoses/import")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteDiagnosisRequest constructs an http.Request for the DeleteDiagnosis method
func NewDeleteDiagnosisRequest(server string, id openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/diagnoses/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetDiagnosisRequest constructs an http.Request for the GetDiagnosis method
func NewGetDiagnosisRequest(server string, id openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/diagnoses/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateDiagnosisRequest calls the generic UpdateDiagnosis builder with application/json body
func NewUpdateDiagnosisRequest(server string, id openapi_types.UUID, body UpdateDiagnosisJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateDiagnosisRequestWithBody(server, id, "application/json", bodyReader)
}

// NewUpdateDiagnosisRequestWithBody constructs an http.Request for the UpdateDiagnosis method, with any body, and a specified content type
func NewUpdateDiagnosisRequestWithBody(server string, id openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/diagnoses/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// ListDiagnosesWithResponse Список активных записей
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/diagnoses (the `ListDiagnoses` operationId).
	ListDiagnosesWithResponse(ctx context.Context, params *ListDiagnosesParams, reqEditors ...RequestEditorFn) (*ListDiagnosesResponse, error)

	// CreateDiagnosisWithBodyWithResponse Создать запись
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1/diagnoses (the `CreateDiagnosis` operationId).
	CreateDiagnosisWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateDiagnosisResponse, error)

	// CreateDiagnosisWithResponse Создать запись
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1/diagnoses (the `CreateDiagnosis` operationId).
	CreateDiagnosisWithResponse(ctx context.Context, body CreateDiagnosisJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateDiagnosisResponse, error)

	// ImportDiagnosesWithBodyWithResponse Импортировать диагнозы из выбранного JSON-файла одной транзакцией
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1/diagnoses/import (the `ImportDiagnoses` operationId).
	ImportDiagnosesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ImportDiagnosesResponse, error)

	// ImportDiagnosesWithResponse Импортировать диагнозы из выбранного JSON-файла одной транзакцией
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1/diagnoses/import (the `ImportDiagnoses` operationId).
	ImportDiagnosesWithResponse(ctx context.Context, body ImportDiagnosesJSONRequestBody, reqEditors ...RequestEditorFn) (*ImportDiagnosesResponse, error)

	// DeleteDiagnosisWithResponse Мягкое удаление
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /api/v1/diagnoses/{id} (the `DeleteDiagnosis` operationId).
	DeleteDiagnosisWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*DeleteDiagnosisResponse, error)

	// GetDiagnosisWithResponse Карточка, включая мягко удалённые записи
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/diagnoses/{id} (the `GetDiagnosis` operationId).
	GetDiagnosisWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetDiagnosisResponse, error)

	// UpdateDiagnosisWithBodyWithResponse Полностью обновить активную запись
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /api/v1/diagnoses/{id} (the `UpdateDiagnosis` operationId).
	UpdateDiagnosisWithBodyWithResponse(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateDiagnosisResponse, error)

	// UpdateDiagnosisWithResponse Полностью обновить активную запись
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /api/v1/diagnoses/{id} (the `UpdateDiagnosis` operationId).
	UpdateDiagnosisWithResponse(ctx context.Context, id openapi_types.UUID, body UpdateDiagnosisJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateDiagnosisResponse, error)
}

type ListDiagnosesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *DiagnosisPage
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Error
	// JSON415 the response for an HTTP 415 `application/json` response
	JSON415 *Error
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *Error
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListDiagnosesResponse) GetJSON200() *DiagnosisPage {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r ListDiagnosesResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r ListDiagnosesResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r ListDiagnosesResponse) GetJSON409() *Error {
	return r.JSON409
}

// GetJSON415 returns the response for an HTTP 415 `application/json` response
func (r ListDiagnosesResponse) GetJSON415() *Error {
	return r.JSON415
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r ListDiagnosesResponse) GetJSON500() *Error {
	return r.JSON500
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r ListDiagnosesResponse) GetJSON503() *Error {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r ListDiagnosesResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListDiagnosesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListDiagnosesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListDiagnosesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateDiagnosisResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *Diagnosis
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Error
	// JSON415 the response for an HTTP 415 `application/json` response
	JSON415 *Error
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *Error
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *Error
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r CreateDiagnosisResponse) GetJSON201() *Diagnosis {
	return r.JSON201
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r CreateDiagnosisResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r CreateDiagnosisResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r CreateDiagnosisResponse) GetJSON409() *Error {
	return r.JSON409
}

// GetJSON415 returns the response for an HTTP 415 `application/json` response
func (r CreateDiagnosisResponse) GetJSON415() *Error {
	return r.JSON415
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r CreateDiagnosisResponse) GetJSON500() *Error {
	return r.JSON500
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r CreateDiagnosisResponse) GetJSON503() *Error {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r CreateDiagnosisResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreateDiagnosisResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateDiagnosisResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateDiagnosisResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ImportDiagnosesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ImportResult
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Error
	// JSON415 the response for an HTTP 415 `application/json` response
	JSON415 *Error
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *Error
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ImportDiagnosesResponse) GetJSON200() *ImportResult {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r ImportDiagnosesResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r ImportDiagnosesResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r ImportDiagnosesResponse) GetJSON409() *Error {
	return r.JSON409
}

// GetJSON415 returns the response for an HTTP 415 `application/json` response
func (r ImportDiagnosesResponse) GetJSON415() *Error {
	return r.JSON415
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r ImportDiagnosesResponse) GetJSON500() *Error {
	return r.JSON500
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r ImportDiagnosesResponse) GetJSON503() *Error {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r ImportDiagnosesResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ImportDiagnosesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ImportDiagnosesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ImportDiagnosesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteDiagnosisResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Error
	// JSON415 the response for an HTTP 415 `application/json` response
	JSON415 *Error
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *Error
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *Error
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r DeleteDiagnosisResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r DeleteDiagnosisResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r DeleteDiagnosisResponse) GetJSON409() *Error {
	return r.JSON409
}

// GetJSON415 returns the response for an HTTP 415 `application/json` response
func (r DeleteDiagnosisResponse) GetJSON415() *Error {
	return r.JSON415
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r DeleteDiagnosisResponse) GetJSON500() *Error {
	return r.JSON500
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r DeleteDiagnosisResponse) GetJSON503() *Error {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r DeleteDiagnosisResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DeleteDiagnosisResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteDiagnosisResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteDiagnosisResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetDiagnosisResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Diagnosis
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Error
	// JSON415 the response for an HTTP 415 `application/json` response
	JSON415 *Error
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *Error
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetDiagnosisResponse) GetJSON200() *Diagnosis {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r GetDiagnosisResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetDiagnosisResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r GetDiagnosisResponse) GetJSON409() *Error {
	return r.JSON409
}

// GetJSON415 returns the response for an HTTP 415 `application/json` response
func (r GetDiagnosisResponse) GetJSON415() *Error {
	return r.JSON415
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r GetDiagnosisResponse) GetJSON500() *Error {
	return r.JSON500
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r GetDiagnosisResponse) GetJSON503() *Error {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r GetDiagnosisResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetDiagnosisResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDiagnosisResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetDiagnosisResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UpdateDiagnosisResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Diagnosis
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Error
	// JSON415 the response for an HTTP 415 `application/json` response
	JSON415 *Error
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *Error
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r UpdateDiagnosisResponse) GetJSON200() *Diagnosis {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r UpdateDiagnosisResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r UpdateDiagnosisResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r UpdateDiagnosisResponse) GetJSON409() *Error {
	return r.JSON409
}

// GetJSON415 returns the response for an HTTP 415 `application/json` response
func (r UpdateDiagnosisResponse) GetJSON415() *Error {
	return r.JSON415
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r UpdateDiagnosisResponse) GetJSON500() *Error {
	return r.JSON500
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r UpdateDiagnosisResponse) GetJSON503() *Error {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r UpdateDiagnosisResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r UpdateDiagnosisResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateDiagnosisResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UpdateDiagnosisResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListDiagnosesWithResponse Список активных записей
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/diagnoses (the `ListDiagnoses` operationId).
func (c *ClientWithResponses) ListDiagnosesWithResponse(ctx context.Context, params *ListDiagnosesParams, reqEditors ...RequestEditorFn) (*ListDiagnosesResponse, error) {
	rsp, err := c.ListDiagnoses(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListDiagnosesResponse(rsp)
}

// CreateDiagnosisWithBodyWithResponse Создать запись
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1/diagnoses (the `CreateDiagnosis` operationId).
func (c *ClientWithResponses) CreateDiagnosisWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateDiagnosisResponse, error) {
	rsp, err := c.CreateDiagnosisWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateDiagnosisResponse(rsp)
}

// CreateDiagnosisWithResponse Создать запись
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1/diagnoses (the `CreateDiagnosis` operationId).
func (c *ClientWithResponses) CreateDiagnosisWithResponse(ctx context.Context, body CreateDiagnosisJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateDiagnosisResponse, error) {
	rsp, err := c.CreateDiagnosis(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateDiagnosisResponse(rsp)
}

// ImportDiagnosesWithBodyWithResponse Импортировать диагнозы из выбранного JSON-файла одной транзакцией
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1/diagnoses/import (the `ImportDiagnoses` operationId).
func (c *ClientWithResponses) ImportDiagnosesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ImportDiagnosesResponse, error) {
	rsp, err := c.ImportDiagnosesWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseImportDiagnosesResponse(rsp)
}

// ImportDiagnosesWithResponse Импортировать диагнозы из выбранного JSON-файла одной транзакцией
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1/diagnoses/import (the `ImportDiagnoses` operationId).
func (c *ClientWithResponses) ImportDiagnosesWithResponse(ctx context.Context, body ImportDiagnosesJSONRequestBody, reqEditors ...RequestEditorFn) (*ImportDiagnosesResponse, error) {
	rsp, err := c.ImportDiagnoses(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseImportDiagnosesResponse(rsp)
}

// DeleteDiagnosisWithResponse Мягкое удаление
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /api/v1/diagnoses/{id} (the `DeleteDiagnosis` operationId).
func (c *ClientWithResponses) DeleteDiagnosisWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*DeleteDiagnosisResponse, error) {
	rsp, err := c.DeleteDiagnosis(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteDiagnosisResponse(rsp)
}

// GetDiagnosisWithResponse Карточка, включая мягко удалённые записи
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/diagnoses/{id} (the `GetDiagnosis` operationId).
func (c *ClientWithResponses) GetDiagnosisWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetDiagnosisResponse, error) {
	rsp, err := c.GetDiagnosis(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDiagnosisResponse(rsp)
}

// UpdateDiagnosisWithBodyWithResponse Полностью обновить активную запись
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /api/v1/diagnoses/{id} (the `UpdateDiagnosis` operationId).
func (c *ClientWithResponses) UpdateDiagnosisWithBodyWithResponse(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateDiagnosisResponse, error) {
	rsp, err := c.UpdateDiagnosisWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateDiagnosisResponse(rsp)
}

// UpdateDiagnosisWithResponse Полностью обновить активную запись
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /api/v1/diagnoses/{id} (the `UpdateDiagnosis` operationId).
func (c *ClientWithResponses) UpdateDiagnosisWithResponse(ctx context.Context, id openapi_types.UUID, body UpdateDiagnosisJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateDiagnosisResponse, error) {
	rsp, err := c.UpdateDiagnosis(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateDiagnosisResponse(rsp)
}

// ParseListDiagnosesResponse parses an HTTP response from a ListDiagnosesWithResponse call
func ParseListDiagnosesResponse(rsp *http.Response) (*ListDiagnosesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListDiagnosesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DiagnosisPage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 415:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON415 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseCreateDiagnosisResponse parses an HTTP response from a CreateDiagnosisWithResponse call
func ParseCreateDiagnosisResponse(rsp *http.Response) (*CreateDiagnosisResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateDiagnosisResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Diagnosis
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 415:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON415 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseImportDiagnosesResponse parses an HTTP response from a ImportDiagnosesWithResponse call
func ParseImportDiagnosesResponse(rsp *http.Response) (*ImportDiagnosesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ImportDiagnosesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ImportResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 415:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON415 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseDeleteDiagnosisResponse parses an HTTP response from a DeleteDiagnosisWithResponse call
func ParseDeleteDiagnosisResponse(rsp *http.Response) (*DeleteDiagnosisResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteDiagnosisResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 415:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON415 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseGetDiagnosisResponse parses an HTTP response from a GetDiagnosisWithResponse call
func ParseGetDiagnosisResponse(rsp *http.Response) (*GetDiagnosisResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDiagnosisResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Diagnosis
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 415:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON415 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseUpdateDiagnosisResponse parses an HTTP response from a UpdateDiagnosisWithResponse call
func ParseUpdateDiagnosisResponse(rsp *http.Response) (*UpdateDiagnosisResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateDiagnosisResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Diagnosis
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 415:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON415 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListDiagnoses Список активных записей
	// (GET /api/v1/diagnoses)
	ListDiagnoses(w http.ResponseWriter, r *http.Request, params ListDiagnosesParams)
	// CreateDiagnosis Создать запись
	// (POST /api/v1/diagnoses)
	CreateDiagnosis(w http.ResponseWriter, r *http.Request)
	// ImportDiagnoses Импортировать диагнозы из выбранного JSON-файла одной транзакцией
	// (POST /api/v1/diagnoses/import)
	ImportDiagnoses(w http.ResponseWriter, r *http.Request)
	// DeleteDiagnosis Мягкое удаление
	// (DELETE /api/v1/diagnoses/{id})
	DeleteDiagnosis(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// GetDiagnosis Карточка, включая мягко удалённые записи
	// (GET /api/v1/diagnoses/{id})
	GetDiagnosis(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// UpdateDiagnosis Полностью обновить активную запись
	// (PUT /api/v1/diagnoses/{id})
	UpdateDiagnosis(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListDiagnoses operation middleware
func (siw *ServerInterfaceWrapper) ListDiagnoses(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListDiagnosesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "include_deleted" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "include_deleted", r.URL.Query(), &params.IncludeDeleted, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "include_deleted"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "include_deleted", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDiagnoses(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDiagnosis operation middleware
func (siw *ServerInterfaceWrapper) CreateDiagnosis(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDiagnosis(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ImportDiagnoses operation middleware
func (siw *ServerInterfaceWrapper) ImportDiagnoses(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ImportDiagnoses(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteDiagnosis operation middleware
func (siw *ServerInterfaceWrapper) DeleteDiagnosis(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", mux.Vars(r)["id"], &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDiagnosis(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDiagnosis operation middleware
func (siw *ServerInterfaceWrapper) GetDiagnosis(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", mux.Vars(r)["id"], &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDiagnosis(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateDiagnosis operation middleware
func (siw *ServerInterfaceWrapper) UpdateDiagnosis(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", mux.Vars(r)["id"], &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateDiagnosis(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL          string
	BaseRouter       *mux.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(options.BaseURL+"/api/v1/diagnoses", wrapper.ListDiagnoses).Methods(http.MethodGet)

	r.HandleFunc(options.BaseURL+"/api/v1/diagnoses", wrapper.CreateDiagnosis).Methods(http.MethodPost)

	r.HandleFunc(options.BaseURL+"/api/v1/diagnoses/{id}", wrapper.DeleteDiagnosis).Methods(http.MethodDelete)

	r.HandleFunc(options.BaseURL+"/api/v1/diagnoses/{id}", wrapper.GetDiagnosis).Methods(http.MethodGet)

	r.HandleFunc(options.BaseURL+"/api/v1/diagnoses/{id}", wrapper.UpdateDiagnosis).Methods(http.MethodPut)

	r.HandleFunc(options.BaseURL+"/api/v1/diagnoses/import", wrapper.ImportDiagnoses).Methods(http.MethodPost)

	return r
}

type ListDiagnosesRequestObject struct {
	Params ListDiagnosesParams
}

type ListDiagnosesResponseObject interface {
	VisitListDiagnosesResponse(w http.ResponseWriter) error
}

type ListDiagnoses200JSONResponse DiagnosisPage

func (response ListDiagnoses200JSONResponse) VisitListDiagnosesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListDiagnoses400JSONResponse Error

func (response ListDiagnoses400JSONResponse) VisitListDiagnosesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListDiagnoses404JSONResponse Error

func (response ListDiagnoses404JSONResponse) VisitListDiagnosesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListDiagnoses409JSONResponse Error

func (response ListDiagnoses409JSONResponse) VisitListDiagnosesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ListDiagnoses415JSONResponse Error

func (response ListDiagnoses415JSONResponse) VisitListDiagnosesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(415)
	_, err := buf.WriteTo(w)
	return err
}

type ListDiagnoses500JSONResponse Error

func (response ListDiagnoses500JSONResponse) VisitListDiagnosesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListDiagnoses503JSONResponse Error

func (response ListDiagnoses503JSONResponse) VisitListDiagnosesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDiagnosisRequestObject struct {
	Body *CreateDiagnosisJSONRequestBody
}

type CreateDiagnosisResponseObject interface {
	VisitCreateDiagnosisResponse(w http.ResponseWriter) error
}

type CreateDiagnosis201JSONResponse Diagnosis

func (response CreateDiagnosis201JSONResponse) VisitCreateDiagnosisResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDiagnosis400JSONResponse Error

func (response CreateDiagnosis400JSONResponse) VisitCreateDiagnosisResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDiagnosis404JSONResponse Error

func (response CreateDiagnosis404JSONResponse) VisitCreateDiagnosisResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDiagnosis409JSONResponse Error

func (response CreateDiagnosis409JSONResponse) VisitCreateDiagnosisResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDiagnosis415JSONResponse Error

func (response CreateDiagnosis415JSONResponse) VisitCreateDiagnosisResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(415)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDiagnosis500JSONResponse Error

func (response CreateDiagnosis500JSONResponse) VisitCreateDiagnosisResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDiagnosis503JSONResponse Error

func (response CreateDiagnosis503JSONResponse) VisitCreateDiagnosisResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type ImportDiagnosesRequestObject struct {
	Body *ImportDiagnosesJSONRequestBody
}

type ImportDiagnosesResponseObject interface {
	VisitImportDiagnosesResponse(w http.ResponseWriter) error
}

type ImportDiagnoses200JSONResponse ImportResult

func (response ImportDiagnoses200JSONResponse) VisitImportDiagnosesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ImportDiagnoses400JSONResponse Error

func (response ImportDiagnoses400JSONResponse) VisitImportDiagnosesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ImportDiagnoses404JSONResponse Error

func (response ImportDiagnoses404JSONResponse) VisitImportDiagnosesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ImportDiagnoses409JSONResponse Error

func (response ImportDiagnoses409JSONResponse) VisitImportDiagnosesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ImportDiagnoses415JSONResponse Error

func (response ImportDiagnoses415JSONResponse) VisitImportDiagnosesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(415)
	_, err := buf.WriteTo(w)
	return err
}

type ImportDiagnoses500JSONResponse Error

func (response ImportDiagnoses500JSONResponse) VisitImportDiagnosesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ImportDiagnoses503JSONResponse Error

func (response ImportDiagnoses503JSONResponse) VisitImportDiagnosesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteDiagnosisRequestObject struct {
	ID openapi_types.UUID `json:"id"`
}

type DeleteDiagnosisResponseObject interface {
	VisitDeleteDiagnosisResponse(w http.ResponseWriter) error
}

type DeleteDiagnosis204Response struct {
}

func (response DeleteDiagnosis204Response) VisitDeleteDiagnosisResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteDiagnosis400JSONResponse Error

func (response DeleteDiagnosis400JSONResponse) VisitDeleteDiagnosisResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteDiagnosis404JSONResponse Error

func (response DeleteDiagnosis404JSONResponse) VisitDeleteDiagnosisResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteDiagnosis409JSONResponse Error

func (response DeleteDiagnosis409JSONResponse) VisitDeleteDiagnosisResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteDiagnosis415JSONResponse Error

func (response DeleteDiagnosis415JSONResponse) VisitDeleteDiagnosisResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(415)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteDiagnosis500JSONResponse Error

func (response DeleteDiagnosis500JSONResponse) VisitDeleteDiagnosisResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteDiagnosis503JSONResponse Error

func (response DeleteDiagnosis503JSONResponse) VisitDeleteDiagnosisResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetDiagnosisRequestObject struct {
	ID openapi_types.UUID `json:"id"`
}

type GetDiagnosisResponseObject interface {
	VisitGetDiagnosisResponse(w http.ResponseWriter) error
}

type GetDiagnosis200JSONResponse Diagnosis

func (response GetDiagnosis200JSONResponse) VisitGetDiagnosisResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetDiagnosis400JSONResponse Error

func (response GetDiagnosis400JSONResponse) VisitGetDiagnosisResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetDiagnosis404JSONResponse Error

func (response GetDiagnosis404JSONResponse) VisitGetDiagnosisResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetDiagnosis409JSONResponse Error

func (response GetDiagnosis409JSONResponse) VisitGetDiagnosisResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetDiagnosis415JSONResponse Error

func (response GetDiagnosis415JSONResponse) VisitGetDiagnosisResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(415)
	_, err := buf.WriteTo(w)
	return err
}

type GetDiagnosis500JSONResponse Error

func (response GetDiagnosis500JSONResponse) VisitGetDiagnosisResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetDiagnosis503JSONResponse Error

func (response GetDiagnosis503JSONResponse) VisitGetDiagnosisResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateDiagnosisRequestObject struct {
	ID   openapi_types.UUID `json:"id"`
	Body *UpdateDiagnosisJSONRequestBody
}

type UpdateDiagnosisResponseObject interface {
	VisitUpdateDiagnosisResponse(w http.ResponseWriter) error
}

type UpdateDiagnosis200JSONResponse Diagnosis

func (response UpdateDiagnosis200JSONResponse) VisitUpdateDiagnosisResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateDiagnosis400JSONResponse Error

func (response UpdateDiagnosis400JSONResponse) VisitUpdateDiagnosisResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateDiagnosis404JSONResponse Error

func (response UpdateDiagnosis404JSONResponse) VisitUpdateDiagnosisResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateDiagnosis409JSONResponse Error

func (response UpdateDiagnosis409JSONResponse) VisitUpdateDiagnosisResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateDiagnosis415JSONResponse Error

func (response UpdateDiagnosis415JSONResponse) VisitUpdateDiagnosisResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(415)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateDiagnosis500JSONResponse Error

func (response UpdateDiagnosis500JSONResponse) VisitUpdateDiagnosisResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateDiagnosis503JSONResponse Error

func (response UpdateDiagnosis503JSONResponse) VisitUpdateDiagnosisResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListDiagnoses Список активных записей
	// (GET /api/v1/diagnoses)
	ListDiagnoses(ctx context.Context, request ListDiagnosesRequestObject) (ListDiagnosesResponseObject, error)
	// CreateDiagnosis Создать запись
	// (POST /api/v1/diagnoses)
	CreateDiagnosis(ctx context.Context, request CreateDiagnosisRequestObject) (CreateDiagnosisResponseObject, error)
	// ImportDiagnoses Импортировать диагнозы из выбранного JSON-файла одной транзакцией
	// (POST /api/v1/diagnoses/import)
	ImportDiagnoses(ctx context.Context, request ImportDiagnosesRequestObject) (ImportDiagnosesResponseObject, error)
	// DeleteDiagnosis Мягкое удаление
	// (DELETE /api/v1/diagnoses/{id})
	DeleteDiagnosis(ctx context.Context, request DeleteDiagnosisRequestObject) (DeleteDiagnosisResponseObject, error)
	// GetDiagnosis Карточка, включая мягко удалённые записи
	// (GET /api/v1/diagnoses/{id})
	GetDiagnosis(ctx context.Context, request GetDiagnosisRequestObject) (GetDiagnosisResponseObject, error)
	// UpdateDiagnosis Полностью обновить активную запись
	// (PUT /api/v1/diagnoses/{id})
	UpdateDiagnosis(ctx context.Context, request UpdateDiagnosisRequestObject) (UpdateDiagnosisResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListDiagnoses operation middleware
func (sh *strictHandler) ListDiagnoses(w http.ResponseWriter, r *http.Request, params ListDiagnosesParams) {
	var request ListDiagnosesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListDiagnoses(ctx, request.(ListDiagnosesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListDiagnoses")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListDiagnosesResponseObject); ok {
		if err := validResponse.VisitListDiagnosesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateDiagnosis operation middleware
func (sh *strictHandler) CreateDiagnosis(w http.ResponseWriter, r *http.Request) {
	var request CreateDiagnosisRequestObject

	var body CreateDiagnosisJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateDiagnosis(ctx, request.(CreateDiagnosisRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateDiagnosis")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateDiagnosisResponseObject); ok {
		if err := validResponse.VisitCreateDiagnosisResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ImportDiagnoses operation middleware
func (sh *strictHandler) ImportDiagnoses(w http.ResponseWriter, r *http.Request) {
	var request ImportDiagnosesRequestObject

	var body ImportDiagnosesJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ImportDiagnoses(ctx, request.(ImportDiagnosesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ImportDiagnoses")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ImportDiagnosesResponseObject); ok {
		if err := validResponse.VisitImportDiagnosesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteDiagnosis operation middleware
func (sh *strictHandler) DeleteDiagnosis(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request DeleteDiagnosisRequestObject

	request.ID = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteDiagnosis(ctx, request.(DeleteDiagnosisRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteDiagnosis")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteDiagnosisResponseObject); ok {
		if err := validResponse.VisitDeleteDiagnosisResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDiagnosis operation middleware
func (sh *strictHandler) GetDiagnosis(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetDiagnosisRequestObject

	request.ID = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDiagnosis(ctx, request.(GetDiagnosisRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDiagnosis")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDiagnosisResponseObject); ok {
		if err := validResponse.VisitGetDiagnosisResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateDiagnosis operation middleware
func (sh *strictHandler) UpdateDiagnosis(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request UpdateDiagnosisRequestObject

	request.ID = id

	var body UpdateDiagnosisJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateDiagnosis(ctx, request.(UpdateDiagnosisRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateDiagnosis")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateDiagnosisResponseObject); ok {
		if err := validResponse.VisitUpdateDiagnosisResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FlLb9tGEP4rwrZH2aJfRcpj46JwEbRBH6fACNbiSN6ALy+XRgyDgB9JU8BBjPbSImhRFP0DsmzB9EP0",
	"X5j9R8UuKYmSKMc1FNUHnswVd3Ze33ycWe+Suuf4nguuCIi5S4L6JjhUP64y2nS9gOmFzz0fuGCgV3XP",
	"AvXXoS+fgNsUm8T8rEoc5uZWYscHYpJAcOY2SVQldQ5UgPWcCiXa8LijnohFBcwJ5gApkLHAhg/IuKFt",
	"0w0biCl4CAVnMGtINgyZVaTKpc6oT4vLQ04tFUiFvvUfnYqqhMNWyDhYxHxGtDG50AwdWU0jnRk3FI71",
	"/sHexguoC2VMP2Nrrh9qg6hlMcE8l9pPcwlsUDuA6jRyep+gjQQg7+GtTj2lTRiHIhPgDD98yqFBTPJJ",
	"bYDsWgbr2gDTUV8V5ZzuqLXNHKajlr1groAmcPXKazQCmPBOeILaRa9GM60N7O3vqeufXeT7l5x7fNxn",
	"6P18m6tadhUEZfaYKekBEzVmUhPLfgwGDQa2FUwGXIHImGYHgiDL8J0A09tf5MWa43tc3KcKrBQgcA9I",
	"peqUJ/TlWiq5YBiGrobeehR0I64NtE/26jsIQlt8xEIohO24PWofcxueThgTioBJnQpqe825APg2q6ss",
	"bQMPmOcSkyzMG/OGriUfXOozYpKleWN+iVSJT8WmtrhGfVbbXqgNZaGZFp7ylaosrlnEJE9YIFb7u9QR",
	"nDoggAfEfLZLmNK4FQLf6VGL2a+3NAQ62dCgOpYrhs4ac0KHmItZztLVIGW5ui5WkBVyoYb8kcbdj9wa",
	"Om2sLoqFmFu3QwueZ1+LYoMy9GdHbnieDdQlUbSush/4nptFf9Ew0tJ3BbhpNfm+zeo6FbUXgcrtbk7B",
	"nUCnqVwjyIKgzpkvUozgP3Ifb7AjXyugLE9RdcqkRSr/xA5eYiL35J56kgfYlUd4UcFzbOGN3MNE7qfW",
	"LM/Gmgp2sYUXeIYd7GKS6v58BrrfY4Jd+QqvMFZx0IoXVmaUgjZ25F4W+sepurkfFDijKlmZCRB+xa48",
	"lAcaBl3symN5XMFE/owxnuAltlJLlmZgyW/YwjbGch9jvFb4kwfyrYJFB8+y5SHeKJhotg5Cx6F8R0n+",
	"jTdaLsHLCrY0mmNsq7DK1xmi9fsOXqhOhDYVXZIBka5HVeJ7QQHhPtYt6uCzkX4kIBBfeNbO9Bki+5gO",
	"f4xUgx+N8dPC9LWX3FRyU8lNU+emBM/xDFupRJ+M5NsJVBRVxxvCGtNNsG5/C3kqbZLzreHH4Kn8gHEn",
	"kjKmrDqbAkqeKnmq5Knp8tTveI03GswHGCvsYrvHWWcYYwtPFaTwXB5VMMbzCrblEZ7IPWwplzHBU0wq",
	"X3//7Tdz8pUG4RW2KpjgmX55UdHhUXvPdYf2E8a3tGOFHLjLrCgd5tSAN86Bq/r3fK9WNB6rqTs3NFpk",
	"lMXyc+MHrk8Lxsbl1MKSmkpqKqlpStT0hzzGUwVn7FTkoeql8Eq7E2Nn4jxXeH/2FYj/mR+McmwrOafk",
	"nAfPOe+xpVuhRL5RJlcr2MZLvJLv5BtsKX+ue6TUpyT5i/b2SAFvcOcUT75xCgsY6kf9b9DZk9TDuNQq",
	"2bFkx5IdHz47/oUJXinUpDLynZr0TvSkpw7Ux+Tv4Q/VjjtcfSktwLd7XBdym5hkUwjfrNVsr07tTS8Q",
	"5iPjkUGi9ejfAAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
